In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("E:\\6th semmmm\\spam\\final_clean.csv")
df.head()

Unnamed: 0  target                                            message  \
0           0       0  "Go until jurong point, crazy.. Available only...   
1           1       0                      Ok lar... Joking wif u oni...   
2           2       1  Free entry in 2 a wkly comp to win FA Cup fina...   
3           3       0  U dun say so early hor... U c already then say...   
4           4       0  "Nah I don't think he goes to usf, he lives ar...   

   num_characters  num_words  num_sentence  \
0             113         26             2   
1              29          8             2   
2             155         37             2   
3              49         13             1   
4              63         17             1   

                                    transformed_text  
0  go jurong point crazi avail bugi n great world...  
1                              ok lar joke wif u oni  
2  free entri 2 wkli comp win fa cup final tkt 21...  
3                u dun say earli hor u c alreadi say  
4               nah think goe usf live around though

In [3]:
df.drop(columns='Unnamed: 0',inplace=True)

In [4]:
df.head()

target                                            message  num_characters  \
0       0  "Go until jurong point, crazy.. Available only...             113   
1       0                      Ok lar... Joking wif u oni...              29   
2       1  Free entry in 2 a wkly comp to win FA Cup fina...             155   
3       0  U dun say so early hor... U c already then say...              49   
4       0  "Nah I don't think he goes to usf, he lives ar...              63   

   num_words  num_sentence                                   transformed_text  
0         26             2  go jurong point crazi avail bugi n great world...  
1          8             2                              ok lar joke wif u oni  
2         37             2  free entri 2 wkli comp win fa cup final tkt 21...  
3         13             1                u dun say earli hor u c alreadi say  
4         17             1               nah think goe usf live around though

In [10]:
df['transformed_text'].fillna('missing',inplace=True)

# model buildings

In [11]:
# applying the bag of words
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
print(" imported sucessfully")

 imported sucessfully


In [6]:
import warnings
warnings.filterwarnings('ignore')


In [12]:
x=cv.fit_transform(df['transformed_text']).toarray()
print(" converted sucessfully")

 converted sucessfully


In [13]:
x.shape

(5126, 6645)

In [14]:
y=df['target'].values

In [17]:
y.shape

(5126,)

In [18]:
# train tests splits
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [22]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((4100, 6645), (1026, 6645), (4100,), (1026,))

In [25]:
# imports the models
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score


In [26]:
gnb=GaussianNB()
mnb=MultinomialNB()
bnb=BernoulliNB()


In [28]:
gnb.fit(X_train,y_train)
y_pred1=gnb.predict(X_test)
print(accuracy_score(y_test,y_pred1))
print(confusion_matrix(y_test,y_pred1))
print(precision_score(y_test,y_pred1))

0.8674463937621832
[[790 116]
 [ 20 100]]
0.46296296296296297


In [30]:
mnb.fit(X_train,y_train)
y_pred2=mnb.predict(X_test)
print(accuracy_score(y_test,y_pred2))
print(confusion_matrix(y_test,y_pred2))
print(precision_score(y_test,y_pred2))

0.9756335282651072
[[891  15]
 [ 10 110]]
0.88


In [31]:
bnb.fit(X_train,y_train)
y_pred3=bnb.predict(X_test)
print(accuracy_score(y_test,y_pred3))
print(confusion_matrix(y_test,y_pred3))
print(precision_score(y_test,y_pred3))

0.9678362573099415
[[901   5]
 [ 28  92]]
0.9484536082474226


# applly for the tfidf

In [34]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()

In [35]:
TF_x=tfidf.fit_transform(df['transformed_text']).toarray()


In [36]:
TF_x.shape

(5126, 6645)

In [37]:
TF_y=df['target'].values

In [38]:
TF_y.shape

(5126,)

In [39]:
x_train,x_test,y__train,y__test=train_test_split(TF_x,TF_y,test_size=0.2,random_state=5)

In [40]:
gnb.fit(x_train,y__train)
y__pred1=gnb.predict(x_test)
print(accuracy_score(y__test,y__pred1))
print(confusion_matrix(y__test,y__pred1))
print(precision_score(y__test,y__pred1))

0.8791423001949318
[[778  98]
 [ 26 124]]
0.5585585585585585


In [41]:
mnb.fit(x_train,y__train)
y__pred2=mnb.predict(x_test)
print(accuracy_score(y__test,y__pred2))
print(confusion_matrix(y__test,y__pred2))
print(precision_score(y__test,y__pred2))

0.9571150097465887
[[876   0]
 [ 44 106]]
1.0


In [42]:
bnb.fit(X_train,y_train)
y__pred3=bnb.predict(x_test)
print(accuracy_score(y__test,y__pred3))
print(confusion_matrix(y__test,y__pred3))
print(precision_score(y__test,y__pred3))

0.9717348927875243
[[873   3]
 [ 26 124]]
0.9763779527559056


In [50]:
# tfidf- mnb

from nltk.corpus import stopwords
import string
from nltk.stem.porter import PorterStemmer
import nltk
import string
def transform_text(text):
    ps=PorterStemmer()
    text=text.lower() 
    text=nltk.word_tokenize(text)
    y=[]
    for i in text:
        if i.isalnum():
            y.append(i)
    text=y[:]
    y.clear()
    
    for i in text:
        if i not in stopwords.words('english') and i not in string.punctuation:
            y.append(i)
    text=y[:]
    y.clear()
    
    for i in text:
        y.append(ps.stem(i))
        
    return ' '.join(y)

In [52]:

transform_text(' hellow my world you are my mother hellow sweet hards')

'hellow world mother hellow sweet hard'

In [74]:
class datapreprocess:
    def __init__(self,text):
        self.message=text
        self.preprocess()
    
    def preprocess(self):
        ps=PorterStemmer()
        self.message=self.message.lower() # convert all the cgaracters into the lower cases 
        self.message=nltk.word_tokenize(self.message)
        y=[]
        for i in self.message:
            if i.isalnum():
                y.append(i)
        text=y[:]
        y.clear()
    
        for i in self.message:
            if i not in stopwords.words('english') and i not in string.punctuation:
                y.append(i)
        text=y[:]
        y.clear()
    
        for i in text:
            y.append(ps.stem(i))
        
        return ' '.join(y)
        